"""
Export optimised hull parameters as ready-to-use Mathematica code.

Generates a .nb-compatible text file containing:
- All numeric parameters
- Symbolic hull equations (cross-section, taper, hull region)
- Code for RegionPlot3D visualisation
- Mass, COM, COB, and stability analysis scaffolding
- STL export command
"""

from __future__ import annotations
from .hull import HullParams, hull_mass, hull_volume
from .analysis import (
    total_mass, center_of_mass_body, find_waterline_upright,
    compute_stability_curve,
)
from . import config


def generate_mathematica_code(params: HullParams) -> str:
    """Return a string of Mathematica code that fully defines the boat design."""

    wl = find_waterline_upright(params)
    com = center_of_mass_body(params)
    stab = compute_stability_curve(params)
    m_hull = hull_mass(params)
    vol = hull_volume(params)
    m_total = total_mass(params)

    code = f'''(* ============================================================ *)
(* Boat Hull Design - Generated by boat-optimization             *)
(* ============================================================ *)

(* ---- Parameters ---- *)
L  = {params.length:.6f};   (* Length [m] *)
W  = {params.beam:.6f};     (* Beam / max width [m] *)
DD = {params.depth:.6f};    (* Depth / hull height [m] *)
n  = {params.flare_exp:.4f};  (* Flare exponent: 1=V, 2=parabolic, >2=flat bottom *)
p  = {params.taper_exp:.4f};  (* Taper exponent *)

(* ---- Material / component properties ---- *)
foamDensity   = {config.FOAM_DENSITY_KG_M3:.4f};    (* kg/m^3 *)
waterDensity  = {config.WATER_DENSITY_KG_M3:.1f};   (* kg/m^3 *)
ballastMass   = {params.ballast_mass:.4f};           (* kg *)
ballastZ      = {params.ballast_z:.6f};              (* ballast COM height [m] *)
mastLength    = {config.MAST_LENGTH_M};              (* m *)
mastRadius    = {config.MAST_RADIUS_M:.6f};          (* m *)
mastDensity   = {config.ALUMINUM_DENSITY_KG_M3:.1f}; (* kg/m^3 *)
mastMass      = Pi * mastRadius^2 * mastLength * mastDensity;
g             = {config.G};

(* ============================================================ *)
(* Hull Equations                                                *)
(* ============================================================ *)

(* Cross-section: bottom surface height as a function of y *)
(* at a station with local beam b                          *)
zBottom[y_, b_] := DD * Abs[2 y / b]^n

(* Beam as a function of longitudinal position x *)
beamAtX[x_] := W * (1 - Abs[2 x / L]^p)

(* Hull region predicate for RegionPlot3D *)
hullRegion[x_, y_, z_] :=
  -L/2 <= x <= L/2 &&
  beamAtX[x] > 0 &&
  -beamAtX[x]/2 <= y <= beamAtX[x]/2 &&
  zBottom[y, beamAtX[x]] <= z <= DD

(* ============================================================ *)
(* Visualisation                                                 *)
(* ============================================================ *)

(* 3D hull plot *)
hullPlot = RegionPlot3D[
  hullRegion[x, y, z],
  {{x, -L/2, L/2}}, {{y, -W/2, W/2}}, {{z, 0, DD}},
  PlotPoints -> 60,
  PlotStyle -> Directive[LightBlue, Opacity[0.6]],
  AxesLabel -> {{"x [m]", "y [m]", "z [m]"}},
  PlotLabel -> "Hull Solid"
]

(* Cross-section at midship *)
crossSectionPlot = RegionPlot[
  zBottom[y, W] <= z <= DD,
  {{y, -W/2, W/2}}, {{z, 0, DD}},
  AxesLabel -> {{"y [m]", "z [m]"}},
  PlotLabel -> "Midship Cross-Section",
  AspectRatio -> Automatic
]

(* Plan view (top-down outline) *)
planPlot = ParametricPlot[
  {{x, beamAtX[x]/2}}, {{x, -beamAtX[x]/2}},
  {{x, -L/2, L/2}},
  AxesLabel -> {{"x [m]", "y [m]"}},
  PlotLabel -> "Plan View",
  AspectRatio -> Automatic
]

(* ============================================================ *)
(* Mass Calculations                                             *)
(* ============================================================ *)

(* Analytical cross-section area at a station with beam b *)
crossSectionArea[b_] := DD * b * n / (n + 1)

(* Hull volume (integrate cross-section area over length) *)
hullVolume = NIntegrate[crossSectionArea[beamAtX[x]], {{x, -L/2, L/2}}]

(* Alternatively, triple integral: *)
(* hullVolume = NIntegrate[1,
     {{x, -L/2, L/2}},
     {{y, -beamAtX[x]/2, beamAtX[x]/2}},
     {{z, zBottom[y, beamAtX[x]], DD}}] *)

hullMass = foamDensity * hullVolume;
totalMass = hullMass + ballastMass + mastMass;

Print["Hull volume:  ", hullVolume, " m^3  (", hullVolume * 10^6, " cm^3)"]
Print["Hull mass:    ", hullMass * 1000, " g"]
Print["Mast mass:    ", mastMass * 1000, " g"]
Print["Total mass:   ", totalMass * 1000, " g"]

(* ============================================================ *)
(* Centre of Mass                                                *)
(* ============================================================ *)

(* Hull z-centroid (analytical for power-law cross-section) *)
zBarHull = DD * (n + 1) / (2 n + 1);

(* Combined COM *)
zCOM = (hullMass * zBarHull + ballastMass * ballastZ + mastMass * mastLength/2) / totalMass;
Print["Centre of mass (z): ", zCOM * 100, " cm"]

(* ============================================================ *)
(* Waterline / Draft (upright equilibrium)                       *)
(* ============================================================ *)

(* Submerged volume as a function of waterline height h *)
submergedArea[h_, b_] := Module[{{yMax}},
  yMax = (b/2) * (h/DD)^(1/n);
  2 * yMax * h * n / (n + 1)
] /; 0 < h < DD

submergedArea[h_, b_] := crossSectionArea[b] /; h >= DD
submergedArea[h_, b_] := 0 /; h <= 0

submergedVolume[h_] := NIntegrate[submergedArea[h, beamAtX[x]], {{x, -L/2, L/2}}]

(* Solve for waterline *)
waterlineHeight = h /. FindRoot[
  submergedVolume[h] == totalMass / waterDensity,
  {{h, DD/2}}
];
Print["Waterline: ", waterlineHeight * 100, " cm"]
Print["Freeboard: ", (DD - waterlineHeight) * 100, " cm"]

(* ============================================================ *)
(* Stability Analysis (Righting Moment vs Heel Angle)            *)
(* ============================================================ *)

(* For each heel angle theta, the hull cross-section rotates.       *)
(* The submerged shape changes, shifting the centre of buoyancy.    *)
(* Righting arm GZ = y_B_world - y_G_world                         *)
(* Righting moment = totalMass * g * GZ                             *)

(* Rotation from body to world frame: *)
(* yWorld = yBody Cos[theta] + zBody Sin[theta]  *)
(* zWorld = -yBody Sin[theta] + zBody Cos[theta] *)

(* NOTE: The full large-angle computation requires numerical        *)
(* integration of the rotated, clipped cross-section at each angle. *)
(* The Python optimiser has already computed these values:           *)

(* Pre-computed stability data from Python analysis *)
heelAngles = {{{_format_array(stab.heel_angles_deg)}}};
rightingMoments = {{{_format_array(stab.righting_moments)}}};
rightingArms = {{{_format_array(stab.righting_arms)}}};

stabilityData = Transpose[{{heelAngles, rightingMoments}}];

stabilityPlot = ListLinePlot[stabilityData,
  PlotLabel -> "Righting Moment vs Heel Angle",
  AxesLabel -> {{"Heel Angle [deg]", "Righting Moment [N*m]"}},
  GridLines -> Automatic,
  Epilog -> {{
    {{Red, Dashed, Line[{{{{{stab.avs_deg:.1f}, -10}}, {{{stab.avs_deg:.1f}, 10}}}}]}},
    Text["AVS = {stab.avs_deg:.1f} deg", {{{stab.avs_deg:.1f}, 0.5}}, {{-1, 0}}]
  }}
]

Print["Angle of Vanishing Stability: ", {stab.avs_deg:.1f}, " deg"]
Print["AVS requirement (>100 deg): ", If[{stab.avs_deg:.1f} > 100, "PASS", "FAIL"]]

(* ============================================================ *)
(* STL Export                                                    *)
(* ============================================================ *)

Export["boatmodel.stl",
  RegionPlot3D[hullRegion[x, y, z],
    {{x, -L/2, L/2}}, {{y, -W/2, W/2}}, {{z, 0, DD}},
    PlotPoints -> 100,
    PlotStyle -> Directive[Blue, Opacity[0.5]]
  ]
]

(* ============================================================ *)
(* Summary                                                       *)
(* ============================================================ *)
Print[""]
Print["=== DESIGN SUMMARY ==="]
Print["Length:   ", L * 100, " cm"]
Print["Beam:     ", W * 100, " cm"]
Print["Depth:    ", DD * 100, " cm"]
Print["Flare n:  ", n]
Print["Taper p:  ", p]
Print["Ballast:  ", ballastMass * 1000, " g at z=", ballastZ * 100, " cm"]
Print["AVS:      ", {stab.avs_deg:.1f}, " deg"]
'''
    return code


def export_mathematica(params: HullParams, filename: str = "boat_design.nb") -> None:
    """Write the Mathematica notebook source to a file."""
    code = generate_mathematica_code(params)
    with open(filename, "w", encoding="utf-8") as f:
        f.write(code)
    print(f"Mathematica code exported to {filename}")


def _format_array(arr, fmt: str = ".6f") -> str:
    """Format a numpy array as a Mathematica list interior: a, b, c, ..."""
    return ", ".join(f"{v:{fmt}}" for v in arr)
